# Generated by Django 2.1.8 on 2019-04-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='orders',
        ),
    ]
