# Generated by Django 2.1.8 on 2019-04-24 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190423_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item_quantity',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 12, 14, 47, 565294, tzinfo=utc)),
        ),
    ]
