# Generated by Django 2.1.8 on 2019-04-25 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190424_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(default=0)),
                ('type_of_food', models.CharField(choices=[('V', 'Veg'), ('NV', 'Non Veg')], default='V', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='type_of_food',
            field=models.CharField(choices=[('V', 'Veg'), ('NV', 'Non Veg')], default='V', max_length=1),
        ),
    ]
