# Generated by Django 2.1.8 on 2019-04-25 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190425_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
